### ISSUE TITLE
App 1207659093 doesn't work with `info`

### ISSUE THREAD

**Issue by miketweaver** [Heroic-Games-Launcher/heroic-gogdl#2]
```
[📦 com.heroicgameslauncher.hgl ~]$ /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1207659093 --token="redacted" --lang=en-US --os windows
[API] INFO: Getting info from products endpoint for id: 1207659093
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Ultima™ 9: Ascension with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 1
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
Traceback (most recent call last):
  File "gogdl/cli.py", line 44, in <module>
  File "gogdl/cli.py", line 41, in main
  File "gogdl/dl/manager.py", line 43, in calculate_download_size
  File "gogdl/dl/manager.py", line 206, in collect_depots
IndexError: string index out of range
[5] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by miketweaver** [comment]
A little more digging:
> check if there are games that still use V1 depots and have DLCs downloadable
This one seems to be V1

**Comment by miketweaver** [comment]
The test build appears to have resolved the issue for both #2 and #3.

**Comment by miketweaver** [comment]
@imLinguin any plans to release these fixes?

**Comment by imLinguin** [comment]
Yes, those will be part of next Heroic release

**Comment by imLinguin** [comment]
Merged to `main`. Like I said this will be a part of next Heroic release
