### ISSUE TITLE
App ID 1434370838 doesn't work

### ISSUE THREAD

**Issue by miketweaver** [Heroic-Games-Launcher/heroic-gogdl#3]
```
C:\Users\user>gogdl.exe info 1434370838 --token="redacted" --lang=en-US --os windows
[API] INFO: Getting info from products endpoint for id: 1434370838
[DOWNLOAD_MANAGER] INFO: Checking compatibility of Windward with windows
[DOWNLOAD_MANAGER] INFO: Game is compatible
[DOWNLOAD_MANAGER] INFO: Depot version: 2
[API] INFO: Getting Dependencies repository
[API] INFO: Getting repository manifest
Traceback (most recent call last):
  File "gogdl\cli.py", line 44, in <module>
  File "gogdl\cli.py", line 41, in main
  File "gogdl\dl\manager.py", line 43, in calculate_download_size
  File "gogdl\dl\manager.py", line 169, in collect_depots
  File "gogdl\dl\objects.py", line 24, in __init__
KeyError: 'compressedSize'
[5756] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by imLinguin** [comment]
Fix merged to `main`
