### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by null-dev** [Heroic-Games-Launcher/heroic-gogdl#33]
I'm getting the following error when attempting to download a game:

```
Exception in thread Thread-1 (print_progressbar):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "gogdl\dl\progressbar.py", line 54, in print_progressbar
ZeroDivisionError: float division by zero
```

Note that although this issue looks similar to https://github.com/Heroic-Games-Launcher/heroic-gogdl/issues/27, it is not the same issue. I'm running the latest commit on master (e3b4dae0c06474c8396ee2aaf3fde462e203b419) and the issue is still present. 

Adding the following code fixes the error:

```python
if time_since_last_update == 0:
    time_since_last_update = 1
```

**Comment by imLinguin** [comment]
Fixed upstream
