### ISSUE TITLE
gogdl hangs

### ISSUE THREAD

**Issue by aidalgol** [Heroic-Games-Launcher/heroic-gogdl#40]
I'm afraid I can't figure out a minimal reproduction for this issue, but I can at least get it to happen consistently.

The launch command for running [Deus Ex](https://www.gog.com/en/game/deus_ex) with the [GMDX mod](https://gmdxmod.com/) hangs indefinitely.
```console
$ LD_LIBRARY_PATH=/home/aidan/.config/heroic/tools/wine/Wine-GE-Proton8-13/lib64:/home/aidan/.config/heroic/tools/wine/Wine-GE-Proton8-13/lib:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/usr/lib:/usr/lib32 INI="Z:\extrapool\aidan\heroic\Deus Ex GOTY\GMDXv9\System\gmdx.ini" USERINI="Z:\extrapool\aidan\heroic\Deus Ex GOTY\GMDXv9\System\GMDXUser.ini" LD_PRELOAD= WINEPREFIX="/extrapool/aidan/heroic/prefixes/Deus Ex GOTY Edition" WINEDLLOVERRIDES=winemenubuilder.exe=d DXVK_HUD=fps WINE_FULLSCREEN_FSR=0 WINEESYNC=1 ORIG_LD_LIBRARY_PATH=/run/opengl-driver/lib:/run/opengl-driver-32/lib:/usr/lib:/usr/lib32 GST_PLUGIN_SYSTEM_PATH_1_0=/home/aidan/.config/heroic/tools/wine/Wine-GE-Proton8-13/lib64/gstreamer-1.0:/home/aidan/.config/heroic/tools/wine/Wine-GE-Proton8-13/lib/gstreamer-1.0 WINEDLLPATH=/home/aidan/.config/heroic/tools/wine/Wine-GE-Proton8-13/lib64/wine:/home/aidan/.config/heroic/tools/wine/Wine-GE-Proton8-13/lib/wine /nix/store/1l717xlqryalk6ij7qpzjdkzad3smac4-heroic-unwrapped-2.9.1/share/heroic/build/bin/linux/gogdl launch "/extrapool/aidan/heroic/Deus Ex GOTY" --override-exe "/extrapool/aidan/heroic/Deus Ex GOTY/System/GMDX.exe" 1207658995 --wine /home/aidan/.config/heroic/tools/wine/Wine-GE-Proton8-13/bin/wine --platform windows
^CTraceback (most recent call last):
  File "/nix/store/phhb11c2vg03vzrbi91zwvxi2ca03xig-gogdl-0.7.3/bin/.gogdl-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/phhb11c2vg03vzrbi91zwvxi2ca03xig-gogdl-0.7.3/lib/python3.10/site-packages/gogdl/cli.py", line 47, in main
    function(arguments, unknown_args)
  File "/nix/store/phhb11c2vg03vzrbi91zwvxi2ca03xig-gogdl-0.7.3/lib/python3.10/site-packages/gogdl/launch.py", line 27, in launch
    wrapper = shlex.split(wrapper_arg)
  File "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/lib/python3.10/shlex.py", line 315, in split
    return list(lex)
  File "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/lib/python3.10/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/lib/python3.10/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
KeyboardInterrupt
```

At @imLinguin's suggestion on the Heroic Discord server, I tried adding `--wrapper gamemoderun`, and then it would launch the game.  Adding `gamemoderun` as a wrapper in the game settings in Heroic also worked around the hanging.

**Comment by imLinguin** [comment]
Could you try gogdl build from main branch?

**Comment by aidalgol** [comment]
The hang does not occur with `main` (commit `89d15f1593cc26f15a5f8f409bb623764c095d37` as of now).
