### ISSUE TITLE
ValueError: Queue is closed when updating game, fails before completing with traceback

### ISSUE THREAD

**Issue by instinctualjealousy** [Heroic-Games-Launcher/heroic-gogdl#57]
I'm using heroic-gogdl via [hawkeye's new Playnite plugin](https://github.com/hawkeye116477/playnite-gog-oss-plugin) which may still be prone to issues- I decided to run the command it was pushing directly to see what was actually happening when the install was failing. I can find instances of this error in other Python projects, but no one's mentioned it for this. I wouldn't think it's Python environment related, given how it isn't retrieved or managed by pip/Python, but it could still be related to something about my system?
```
C:\Users\Adam>gogdl_windows_x86_64 --auth-config-path C:\Users\Adam\AppData\Roaming\Playnite\ExtensionsData\03689811-3f33-4dfb-a121-2ee168fb9a5c\tokens.json update 1207659238 --path "D:\GOGLibrary\The King of Fighters 2002\\" --build 50167263047686887 --platform windows --skip-dlcs
[GENERIC DOWNLOAD_MANAGER] INFO: Depot version: 1
[V1] INFO: Initialized V1 Download Manager
[V1] INFO: Deleted: 0 New: 0 Changed: 0
[API] INFO: Getting Dependencies repository
(2.440077781677246, 'MB') 2558607
(7.332484245300293, 'MB') 7688667
[PROGRESS] INFO: = Progress: 0.00 0/7688667, Running for: 00:00:00, ETA: 00:00:00
[PROGRESS] INFO: = Downloaded: 0.00 MiB, Written: 0.00 MiB
[PROGRESS] INFO:  + Download    - 0.00 MiB/s (raw) / 0.00 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk        - 0.00 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 4.55 349952/7688667, Running for: 00:00:01, ETA: 00:00:41
[PROGRESS] INFO: = Downloaded: 0.11 MiB, Written: 0.33 MiB
[PROGRESS] INFO:  + Download    - 0.06 MiB/s (raw) / 0.17 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk        - 0.17 MiB/s (write) / 0.00 MiB/s (read)
[PROGRESS] INFO: = Progress: 18.93 1455360/7688667, Running for: 00:00:03, ETA: 00:00:14
[PROGRESS] INFO: = Downloaded: 1.53 MiB, Written: 1.39 MiB
[PROGRESS] INFO:  + Download    - 0.70 MiB/s (raw) / 2.31 MiB/s (decompressed)
[PROGRESS] INFO:  + Disk        - 1.50 MiB/s (write) / 0.00 MiB/s (read)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "gogdl\dl\progressbar.py", line 44, in loop
  File "multiprocessing\queues.py", line 100, in get
ValueError: Queue <multiprocessing.queues.Queue object at 0x00000258BEE21C40> is closed
```

**Comment by instinctualjealousy** [comment]
I was able to fresh install Jazz Jackrabbit 2 and King of Fighters 2002- which haven't been installed by Galaxy prior. I thought maybe gogdl found something weird about the games that were already installed prior by GOG Galaxy- but I got another fail-right-before-finish when trying to fresh install Jazz Jackrabbit 2: Christmas Chronicles. I'm only really using these games to test since they're small downloads.

**Comment by hawkeye116477** [comment]
For me that `<ValueError: Queue <multiprocessing.queues.Queue>`very often happens at the end of download, but looks like download is fully complete despite that.
